# Generated by Django 3.2.6 on 2023-12-12 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Code', models.CharField(max_length=255)),
                ('Product_Price', models.IntegerField()),
                ('Product_Detial', models.CharField(max_length=255)),
                ('Is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping_Price',
            fields=[
                ('Shipping_Pric_id', models.AutoField(primary_key=True, serialize=False)),
                ('Shipping_Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Token_Line',
            fields=[
                ('Token_id', models.AutoField(primary_key=True, serialize=False)),
                ('Token_Code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Img',
            fields=[
                ('Product_Img_id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Img', models.ImageField(upload_to='reports/')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebEcom.product')),
            ],
        ),
        migrations.CreateModel(
            name='Orderhis',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('Order_code', models.CharField(max_length=255)),
                ('t1', models.CharField(max_length=255, null=True)),
                ('t2', models.CharField(max_length=255, null=True)),
                ('log_img', models.ImageField(upload_to='order/')),
                ('color', models.CharField(max_length=255, null=True)),
                ('t3', models.TextField(null=True)),
                ('t4', models.CharField(max_length=255, null=True)),
                ('t5', models.TextField(null=True)),
                ('create_at', models.DateTimeField()),
                ('status', models.BooleanField(default=False, null=True)),
                ('status_change', models.DateTimeField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebEcom.product')),
            ],
        ),
    ]
