# Generated by Django 3.2.6 on 2023-12-12 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebEcom', '0002_delete_orderhis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderhis',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('Order_code', models.CharField(max_length=255)),
                ('t1', models.CharField(max_length=255, null=True)),
                ('t2', models.CharField(max_length=255, null=True)),
                ('log_img', models.ImageField(upload_to='order/')),
                ('color', models.CharField(max_length=255, null=True)),
                ('t3', models.TextField(null=True)),
                ('t4', models.CharField(max_length=255, null=True)),
                ('t5', models.TextField(null=True)),
                ('create_at', models.DateTimeField()),
                ('status', models.BooleanField(default=False, null=True)),
                ('status_change', models.DateTimeField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebEcom.product')),
            ],
        ),
    ]
