# Generated by Django 3.2.6 on 2023-12-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebEcom', '0003_alter_product_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_Price',
            fields=[
                ('Shipping_Pric_id', models.AutoField(primary_key=True, serialize=False)),
                ('Shipping_Price', models.IntegerField()),
            ],
        ),
    ]
