# Generated by Django 3.2.6 on 2023-12-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebEcom', '0004_orderhis_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhis',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
