# Generated by Django 3.2.6 on 2023-12-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebEcom', '0005_orderhis_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhis',
            name='t6',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
