# Generated by Django 3.2.6 on 2023-12-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebEcom', '0006_orderhis_t6'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhis',
            name='t7',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
